# Generated by Django 5.0.5 on 2024-05-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_quarto_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(default=0, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
